# @package _global_

cdsb: False

# data
Dataset: custom_source
data:
  dataset: "custom"
  image_size: 64   # must be 32, 64, 160, or 256
  channels: 3

# transfer
transfer: True
Dataset_transfer: custom_target

# paths to your image folders (relative to the data/ directory, or absolute)
custom_source_dir: custom_source   # data/custom_source/<class_subdir>/img.jpg
custom_target_dir: custom_target   # data/custom_target/<class_subdir>/img.jpg

final_adaptive: False
adaptive_mean: False
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: 1 * torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])

# device
device: cuda
num_workers: 2
pin_memory: False

# logging
log_stride: 100
gif_stride: 500
plot_npar: 8
test_npar: 100
test_batch_size: 16
cache_npar: 500
cache_batch_size: 50
num_repeat_data: 1
cache_refresh_stride: 500

# training
use_prev_net: True
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
batch_size: 8
num_iter: 2000
n_ipf: 30
lr: 0.0001

num_steps: 30
